In [1]:
import numpy as np
import pandas as pd

In [5]:
material_df.isnull().sum()

material_id               0
material_description      0
material_category         0
sub_category              0
manufacturer            350
manufacturer_part_no    247
uom                     200
plant_id                  0
vendor_id               300
unit_price                0
currency                  0
lead_time_days          149
created_date              0
last_updated              0
dtype: int64

In [4]:
material_df = pd.read_csv("material_master_raw.csv")
vendor_df = pd.read_csv("vendor_master.csv")
plant_df = pd.read_csv("plant_master.csv")

In [6]:
material_df.head()

,material_id,material_description,material_category,sub_category,manufacturer,manufacturer_part_no,uom,plant_id,vendor_id,unit_price,currency,lead_time_days,created_date,last_updated
0,MAT00001,Fire Extinguisher 100 X729,Safety,Fire,S.K.F.,X729-100,Pcs,KOL01,VEN062,274.98,INR,73.0,2026-03-19,2026-08-10
1,MAT00002,Control Valve 100 A823,Instrumentation,Valve,SKF INDIA LTD,A823-100,M,KOL01,VEN063,56.99,USD,25.0,2025-12-03,2026-09-07
2,MAT00003,Control Valve 12 B202,Instrumentation,Valve,BOSCH INDIA,B202-12,L,PUN01,VEN053,175.06,USD,51.0,2025-06-01,2026-04-14
3,MAT00004,Pressure Sensor 100 B641,Instrumentation,Sensor,S.K.F.,B641-100,each,AMD01,VEN035,202.09,INR,90.0,2026-02-07,2026-02-25
4,MAT00005,Safety Shoes 20 Z363,Safety,PPE,Robert Bosch,Z363-20,KG,CHE01,VEN011,457.41,USD,71.0,2025-01-03,2025-07-25

In [7]:
material_df.dtypes

material_id              object
material_description     object
material_category        object
sub_category             object
manufacturer             object
manufacturer_part_no     object
uom                      object
plant_id                 object
vendor_id                object
unit_price              float64
currency                 object
lead_time_days          float64
created_date             object
last_updated             object
dtype: object

In [8]:
vendor_df.head()

  vendor_id                  vendor_name vendor_country
0    VEN001  Vendor A Industrial Pvt Ltd          India
1    VEN002  Vendor B Industrial Pvt Ltd      Singapore
2    VEN003  Vendor C Industrial Pvt Ltd            UAE
3    VEN004  Vendor D Industrial Pvt Ltd            UAE
4    VEN005  Vendor E Industrial Pvt Ltd            UAE

In [9]:
plant_df.head()

  plant_id       plant_name       city region
0    HYD01  Hyderabad Plant  Hyderabad  South
1    BLR01  Bangalore Plant  Bangalore  South
2    MUM01     Mumbai Plant     Mumbai   West
3    PUN01       Pune Plant       Pune   West
4    CHE01    Chennai Plant    Chennai  South

In [10]:
vendor_df.dtypes

vendor_id         object
vendor_name       object
vendor_country    object
dtype: object

In [12]:
plant_df.dtypes

plant_id      object
plant_name    object
city          object
region        object
dtype: object

In [15]:
material_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   material_id           10000 non-null  object
 1   material_description  10000 non-null  object
 2   material_category     10000 non-null  object
 3   sub_category          10000 non-null  object
 4   manufacturer          9650 non-null   object
 5   manufacturer_part_no  9753 non-null   object
 6   uom                   9800 non-null   object
 7   plant_id              10000 non-null  object
 8   vendor_id             9700 non-null   object
 9   unit_price            10000 non-null  float64
 10  currency              10000 non-null  object
 11  lead_time_days        9851 non-null   float64
 12  created_date          10000 non-null  object
 13  last_updated          10000 non-null  object
dtypes: float64(2), object(12)
memory usage: 1.1+ MB

In [16]:
print(
    "Duplicate material IDs:",
    material_df["material_id"].duplicated().sum()
)

Duplicate material IDs: 0

In [18]:

df = material_df.copy()

In [20]:
df.columns = df.columns.str.strip().str.lower()
vendor_df.columns = vendor_df.columns.str.strip().str.lower()
plant_df.columns = plant_df.columns.str.strip().str.lower()

In [21]:
df.columns

Index(['material_id', 'material_description', 'material_category',
       'sub_category', 'manufacturer', 'manufacturer_part_no', 'uom',
       'plant_id', 'vendor_id', 'unit_price', 'currency', 'lead_time_days',
       'created_date', 'last_updated'],
      dtype='object')

In [23]:
df["material_id"].dtypes

dtype('O')

In [24]:
def id_cleaned(data,id_columns):
  for col in id_columns:
    data[col]=(data[col].astype("string").str.strip())
  return data

In [25]:
df=id_cleaned(df,["material_id","vendor_id","plant_id"])
vendor_df=id_cleaned(vendor_df,["vendor_id"])
plant_df=id_cleaned(plant_df,["plant_id"])

In [ ]:
text_col=[]

In [27]:
df.dtypes

material_id             string[python]
material_description            object
material_category               object
sub_category                    object
manufacturer                    object
manufacturer_part_no            object
uom                             object
plant_id                string[python]
vendor_id               string[python]
unit_price                     float64
currency                        object
lead_time_days                 float64
created_date                    object
last_updated                    object
dtype: object

In [28]:
df.columns

Index(['material_id', 'material_description', 'material_category',
       'sub_category', 'manufacturer', 'manufacturer_part_no', 'uom',
       'plant_id', 'vendor_id', 'unit_price', 'currency', 'lead_time_days',
       'created_date', 'last_updated'],
      dtype='object')

In [29]:
text_column = [
    "material_description",
    "material_category",
    "sub_category",
    "manufacturer",
    "manufacturer_part_no",
    "uom",
    "vendor_id",
    "plant_id",
    "currency"
]

for col in text_column:

    if col in df.columns:

        df[col] = (
            df[col]
            .astype("string")
            .str.strip()
        )

In [31]:
df[df["manufacturer"].isnull()]

,material_id,material_description,material_category,sub_category,manufacturer,manufacturer_part_no,uom,plant_id,vendor_id,unit_price,currency,lead_time_days,created_date,last_updated
75,MAT00076,Roller Bearing 200 X891,Mechanical,Bearing,<NA>,X891-200,LTR,AMD01,VEN034,240.43,XYZ,46.0,2025-05-01,2026-09-03
81,MAT00082,Limit Switch 150 X503,Electrical,Switch,<NA>,X503-150,Pcs,PUN01,VEN025,467.54,INR,14.0,2024-01-02,2024-05-26
110,MAT00111,Safety Harness 100 Z766,Safety,Protection,<NA>,Z766-100,L,BLR01,VEN068,76.52,AED,83.0,2025-05-18,2025-06-13
166,MAT00167,Control Cable 200 Z440,Electrical,Cable,<NA>,Z440-200,Pcs,CHE01,VEN010,993.45,INR,17.0,2024-06-16,2025-05-08
197,MAT00198,Spur Gear 150 X387,Mechanical,Gear,<NA>,X387-150,EA,PUN01,VEN040,464.15,INR,74.0,2026-02-17,2026-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9809,MAT09810,Control Valve 150 C198,Mechanical,Coupling,<NA>,B369-40,Kg,KOL01,VEN042,1314.52,AED,49.0,2025-05-10,2026-05-28
9875,MAT09876,Pressure Sensor 150 X373,Instrumentation,Sensor,<NA>,X373-150,Each,MUM01,VEN023,228.74,USD,50.0,2025-05-29,2025-11-26
9889,MAT09890,Safety Shoes 16 A489,Safety,PPE,<NA>,A489-16,Pcs,BLR01,VEN036,483.97,AED,39.0,2026-02-12,2026-03-01
9962,MAT09963,Power Cable 80 X354,Electrical,Cable,<NA>,X354-80,Meter,AMD01,VEN028,23.22,AED,21.0,2024-04-25,2024-08-27
9983,MAT09984,Ball Valve 32 C455,Instrumentation,Valve,<NA>,C455-32,KG,KOL01,VEN055,446.18,INR,39.0,2024-09-18,2025-12-14

In [32]:
missing_values = [
    "",
    "NA",
    "N/A",
    "NULL",
    "null",
    "None",
    "none",
    "NaN",
    "nan"
]

df = df.replace(missing_values, pd.NA)

In [33]:
df.isnull().sum()

material_id               0
material_description      0
material_category         0
sub_category              0
manufacturer            350
manufacturer_part_no    247
uom                     200
plant_id                  0
vendor_id               300
unit_price                0
currency                  0
lead_time_days          149
created_date              0
last_updated              0
dtype: int64

In [34]:
df[df["manufacturer"].isnull()]

,material_id,material_description,material_category,sub_category,manufacturer,manufacturer_part_no,uom,plant_id,vendor_id,unit_price,currency,lead_time_days,created_date,last_updated
75,MAT00076,Roller Bearing 200 X891,Mechanical,Bearing,<NA>,X891-200,LTR,AMD01,VEN034,240.43,XYZ,46.0,2025-05-01,2026-09-03
81,MAT00082,Limit Switch 150 X503,Electrical,Switch,<NA>,X503-150,Pcs,PUN01,VEN025,467.54,INR,14.0,2024-01-02,2024-05-26
110,MAT00111,Safety Harness 100 Z766,Safety,Protection,<NA>,Z766-100,L,BLR01,VEN068,76.52,AED,83.0,2025-05-18,2025-06-13
166,MAT00167,Control Cable 200 Z440,Electrical,Cable,<NA>,Z440-200,Pcs,CHE01,VEN010,993.45,INR,17.0,2024-06-16,2025-05-08
197,MAT00198,Spur Gear 150 X387,Mechanical,Gear,<NA>,X387-150,EA,PUN01,VEN040,464.15,INR,74.0,2026-02-17,2026-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9809,MAT09810,Control Valve 150 C198,Mechanical,Coupling,<NA>,B369-40,Kg,KOL01,VEN042,1314.52,AED,49.0,2025-05-10,2026-05-28
9875,MAT09876,Pressure Sensor 150 X373,Instrumentation,Sensor,<NA>,X373-150,Each,MUM01,VEN023,228.74,USD,50.0,2025-05-29,2025-11-26
9889,MAT09890,Safety Shoes 16 A489,Safety,PPE,<NA>,A489-16,Pcs,BLR01,VEN036,483.97,AED,39.0,2026-02-12,2026-03-01
9962,MAT09963,Power Cable 80 X354,Electrical,Cable,<NA>,X354-80,Meter,AMD01,VEN028,23.22,AED,21.0,2024-04-25,2024-08-27
9983,MAT09984,Ball Valve 32 C455,Instrumentation,Valve,<NA>,C455-32,KG,KOL01,VEN055,446.18,INR,39.0,2024-09-18,2025-12-14

In [35]:
df["unit_price"] = pd.to_numeric(df["unit_price"],errors="coerce")

df["lead_time_days"] = pd.to_numeric(df["lead_time_days"],errors="coerce")

In [36]:
df[df["unit_price"].isnull()]

Empty DataFrame
Columns: [material_id, material_description, material_category, sub_category, manufacturer, manufacturer_part_no, uom, plant_id, vendor_id, unit_price, currency, lead_time_days, created_date, last_updated]
Index: []

In [37]:
df["unit_price"].isnull().sum()

np.int64(0)

In [39]:
df["created_date"]=pd.to_datetime(df["created_date"],errors="coerce")
df["last_updated"]=pd.to_datetime(df["last_updated"],errors="coerce")

In [41]:
df["manufacturer"].head()

0           S.K.F.
1    SKF INDIA LTD
2      BOSCH INDIA
3           S.K.F.
4     Robert Bosch
Name: manufacturer, dtype: string

In [42]:
df["manufacturer"] = (
    df["manufacturer"]
    .astype("string")
    .str.upper()
    .str.replace(".", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

manufacturer_mapping = {

    "SKF INDIA": "SKF",
    "SKF INDIA LTD": "SKF",
    "SKF INDIA LIMITED": "SKF",
    "SKFINDA": "SKF",

    "ABB INDIA": "ABB",
    "ABB INDIA LTD": "ABB",
    "ABB INDIA LIMITED": "ABB",

    "BOSCH INDIA": "BOSCH",
    "BOSCH INDIA LTD": "BOSCH",
    "BOSCH INDIA LIMITED": "BOSCH"
}

df["manufacturer"] = df["manufacturer"].replace(
    manufacturer_mapping
)

In [43]:
df.columns

Index(['material_id', 'material_description', 'material_category',
       'sub_category', 'manufacturer', 'manufacturer_part_no', 'uom',
       'plant_id', 'vendor_id', 'unit_price', 'currency', 'lead_time_days',
       'created_date', 'last_updated'],
      dtype='object')

In [44]:
df['currency']=df['currency'].astype("string").str.strip()

In [45]:
df['currency']=df['currency'].str.upper()

In [47]:
valid_currencies = {
    "INR",
    "USD",
    "AED"
}

df["currency_valid"] = (
    df["currency"].isin(valid_currencies)
)

In [51]:
df[df['currency_valid']==False]

,material_id,material_description,material_category,sub_category,manufacturer,manufacturer_part_no,uom,plant_id,vendor_id,unit_price,currency,lead_time_days,created_date,last_updated,currency_valid
20,MAT00021,Fire Hose 16 Z822,Safety,Fire,SKF,Z822-16,LTR,DEL01,VEN007,150.780000,XYZ,12.0,2026-05-25,2026-10-01,False
56,MAT00057,Instrumentation Cable 12 B640,Electrical,Cable,PARKER,B640-12,KG,MUM01,VEN041,2752.910000,XYZ,87.0,2025-02-08,2026-03-01,False
75,MAT00076,Roller Bearing 200 X891,Mechanical,Bearing,<NA>,X891-200,LTR,AMD01,VEN034,240.430000,XYZ,46.0,2025-05-01,2026-09-03,False
105,MAT00106,Tapered Roller Bearing 80 A446,Mechanical,Bearing,SIEMENS,A446-80,EA,CHE01,VEN068,-1652.086517,XYZ,6.0,2025-02-08,2025-05-12,False
511,MAT00512,Power Cable 32 X399,Electrical,Cable,THE TIMKEN COMPANY,X399-32,M,DEL01,VEN063,1309.720000,XYZ,46.0,2024-01-18,2024-11-11,False
739,MAT00740,Ball Valve 200 Z183,Instrumentation,Valve,EMERSON ELECTRIC,Z183-200,EA,PUN01,VEN037,206.110000,XYZ,88.0,2026-05-09,2026-10-01,False
753,MAT00754,Proximity Sensor 150 B243,Instrumentation,Sensor,FESTO,B243-150,EA,DEL01,VEN058,83.130000,XYZ,37.0,2026-02-08,2026-08-06,False
1074,MAT01075,Control Valve 20 Z567,Instrumentation,Valve,PARKER,Z567-20,EA,PUN01,VEN057,353.030000,XYZ,14.0,2024-09-09,2025-01-10,False
1169,MAT01170,Flexible Coupling 32 Z146,Instrumentation,Sensor,SKF,B522-50,EA,PUN01,VEN025,311.660000,XYZ,21.0,2026-05-31,2026-10-01,False
1576,MAT01577,Proximity Sensor 20 X685,Instrumentation,Sensor,EMERSON INDIA,X685-20,LTR,HYD01,VEN057,547.160000,XYZ,12.0,2024-09-16,2025-07-09,False
1577,MAT01578,C605 40 Gear Spur,Electrical,Cable,HONEYWELL INDIA,X247-40,EA,CHE01,VEN028,196.530000,XYZ,84.0,2024-05-13,2025-07-19,False
2126,MAT02127,Pressure Switch 100 B354,Electrical,Switch,FESTO,B354-100,LTR,AMD01,VEN047,109.970000,XYZ,65.0,2024-01-14,2025-02-13,False
2367,MAT02368,Selector Switch 80 X332,Electrical,Switch,EMERSON ELECTRIC,X332-80,EA,CHE01,VEN076,199.900000,XYZ,71.0,2024-12-13,2025-03-09,False
2397,MAT02398,Instrumentation Cable 150 Z984,Electrical,Cable,FESTO AG,Z984-150,M,HYD01,VEN077,551.890000,XYZ,63.0,2024-10-19,2025-10-28,False
2430,MAT02431,Servo Motor 150 B597,Electrical,Motor,BOSCH,B597-150,KG,HYD01,VEN033,176.700000,XYZ,10.0,2024-05-11,2024-09-13,False
2587,MAT02588,Respirator 65 C994,Safety,Protection,FESTO,C994-65,EA,CHE01,VEN047,135.580000,XYZ,8.0,2026-04-15,2026-10-01,False
2745,MAT02746,Roller Bearing 150 C769,Mechanical,Bearing,SCHNEIDER ELEC,C769-150,EA,DEL01,VEN027,57.430000,XYZ,3.0,2024-09-02,2025-03-14,False
3074,MAT03075,Jaw Coupling 65 B713,Mechanical,Coupling,SIEMENS LTD,B713-65,M,MUM01,VEN022,240.740000,XYZ,29.0,2026-06-01,2026-09-05,False
3357,MAT03358,Spur Gear 50 X701,Mechanical,Gear,SKF,X701-50,KG,HYD01,VEN071,533.540000,XYZ,50.0,2025-11-25,2026-08-14,False
3605,MAT03606,Control Valve 32 Z745,Instrumentation,Valve,HONEYWELL INDIA,Z745-32,EA,HYD01,VEN009,1100.420000,XYZ,29.0,2026-03-31,2026-04-22,False
3723,MAT03724,Control Cable 20 A615,Electrical,Cable,SKF,A615-20,KG,PUN01,VEN050,840.670000,XYZ,77.0,2026-03-14,2026-06-03,False
3764,MAT03765,Jaw Coupling 16 A409,Mechanical,Coupling,EMERSON INDIA,A409-16,EA,AMD01,VEN047,93.860000,XYZ,80.0,2024-09-19,2025-08-06,False
3794,MAT03795,Roller Bearing 20 X418,Mechanical,Bearing,ABB,X418-20,EA,HYD01,VEN030,290.320000,XYZ,89.0,2024-12-31,2025-08-09,False
3819,MAT03820,Respirator 16 Z432,Safety,Protection,ABB,Z432-16,EA,BLR01,VEN043,379.360000,XYZ,21.0,2025-04-26,2025-09-27,False
4013,MAT04014,Limit Switch 50 B392,Electrical,Switch,THE TIMKEN COMPANY,B392-50,<NA>,CHE01,VEN010,27.310000,XYZ,39.0,2025-04-04,2026-08-10,False
4062,MAT04063,Fire Extinguisher 12 X540,Safety,Fire,FESTO,X540-12,KG,CHE01,VEN049,316.350000,XYZ,39.0,2024-10-25,2025-05-22,False
4113,MAT04114,Flow Gauge 12 A809,Instrumentation,Gauge,SCHNEIDER,A809-12,EA,BLR01,VEN072,296.750000,XYZ,21.0,2025-07-17,2025-12-17,False
4133,MAT04134,Bevel Gear 80 C382,Mechanical,Gear,SKF,C382-80,EA,CHE01,VEN047,103.070000,XYZ,12.0,2024-09-15,2025-12-20,False
4134,MAT04135,Spur Gear 32 X196,Mechanical,Gear,HONEYWELL INDIA,X196-32,LTR,DEL01,VEN074,759.660000,XYZ,46.0,2024-06-13,2024-08-04,False
4242,MAT04243,Respirator 12 Z644,Safety,Protection,SCHNEIDER ELECTRIC,Z644-12,KG,KOL01,VEN041,650.260000,XYZ,10.0,2025-08-28,2025-12-07,False
4587,MAT04588,Pressure Gauge 40 B739,Instrumentation,Gauge,PARKER HANNIFIN INDIA,B739-40,EA,HYD01,VEN060,130.280000,XYZ,48.0,2024-05-25,2024-12-07,False
4662,MAT04663,Ball Valve 25 A509,Instrumentation,Valve,TIMKEN,A509-25,EA,KOL01,VEN051,60.300000,XYZ,36.0,2025-06-15,2026-09-12,False
4780,MAT04781,Spur Gear 200 X598,Safety,Fire,FESTO AG,Z958-32,<NA>,AMD01,VEN011,1161.640000,XYZ,20.0,2024-05-01,2025-03-25,False
4786,MAT04787,Temperature Gauge 10 X762,Instrumentation,Gauge,<NA>,X762-10,M,HYD01,VEN069,87.440000,XYZ,29.0,2025-05-11,2025-08-16,False
4930,MAT04931,Instrumentation Cable 20 X398,Electrical,Cable,PARKER HANNIFIN INDIA,X398-20,LTR,BLR01,VEN024,526.780000,XYZ,43.0,2025-02-25,2025-08-18,False
5060,MAT05061,Pressure Switch 16 X756,Electrical,Switch,SCHNEIDER ELECTRIC,<NA>,EA,MUM01,VEN060,66.190000,XYZ,37.0,2024-07-14,2025-05-28,False
5178,MAT05179,Ball Bearing 40 B207,Mechanical,Bearing,SCHNEIDER ELECTRIC,B207-40,EA,KOL01,VEN023,8.240000,XYZ,50.0,2025-05-03,2026-05-29,False
5294,MAT05295,Fire Extinguisher 80 X570,Safety,Fire,HONEYWELL INDIA,X570-80,EA,PUN01,VEN044,52.430000,XYZ,29.0,2025-10-19,2026-08-10,False
5462,MAT05463,Face Shield 150 C923,Safety,Protection,EMERSON INDIA,C923-150,EA,HYD01,VEN046,381.010000,XYZ,88.0,2025-03-21,2025-10-15,False
5465,MAT05466,Jaw Coupling 50 A366,Mechanical,Coupling,SCHNEIDER ELECTRIC,A366-50,LTR,MUM01,VEN068,521.310000,XYZ,4.0,2026-01-06,2026-10-01,False
5671,MAT05672,Tapered Roller Bearing 25 C248,Mechanical,Bearing,HONEYWELL INTL,C248-25,EA,CHE01,VEN076,54.270000,XYZ,45.0,2026-03-20,2026-10-01,False
5824,MAT05825,Temperature Gauge 12 X735,Instrumentation,Gauge,ROBERT BOSCH,X735-12,LTR,PUN01,VEN008,54.250000,XYZ,15.0,2025-10-05,2026-10-01,False
5841,MAT05842,Roller Bearing 40 C630,Mechanical,Bearing,BOSCH,C630-40,KG,PUN01,VEN047,60.910000,XYZ,85.0,2024-05-09,2025-03-30,False
6662,MAT06663,Fire Alarm 16 Z768,Safety,Fire,FESTO AG,Z768-16,EA,AMD01,VEN062,207.050000,XYZ,87.0,2024-12-01,2026-01-30,False
6745,MAT06746,Safety Harness 10 X220,Safety,Protection,PARKER HANNIFIN,X220-10,EA,DEL01,VEN004,318.600000,XYZ,85.0,2024-07-23,2024-11-30,False
6991,MAT06992,Control Cable 150 A838,Electrical,Cable,SIEMENS LTD,A838-150,M,CHE01,VEN036,605.550000,XYZ,76.0,2024-03-06,2024-12-12,False
7065,MAT07066,Tapered Roller Bearing 25 C180,Mechanical,Bearing,SCHNEIDER ELECTRIC,C180-25,LTR,KOL01,VEN043,61.280000,XYZ,67.0,2024-02-09,2025-01-15,False
7282,MAT07283,Respirator 12 B426,Safety,Protection,THE TIMKEN COMPANY,B426-12,LTR,KOL01,VEN022,458.360000,XYZ,26.0,2025-07-29,2025-07-30,False
7359,MAT07360,Safety Helmet 10 C343,Safety,PPE,TIMKEN,C343-10,LTR,HYD01,VEN031,1020.110000,XYZ,52.0,2024-02-02,2024-03-16,False
7694,MAT07695,Flow Gauge 12 Z582,Instrumentation,Gauge,THE TIMKEN COMPANY,Z582-12,EA,KOL01,VEN078,407.850000,XYZ,59.0,2025-03-04,2026-06-28,False
7721,MAT07722,Spur Gear 50 C253,Mechanical,Gear,BOSCH,C253-50,LTR,AMD01,VEN033,-1523.073414,XYZ,29.0,2025-06-11,2026-04-06,False
7899,MAT07900,Fire Hose 32 A112,Safety,Fire,SIEMENS INDIA,A112-32,M,CHE01,VEN058,257.990000,XYZ,43.0,2024-06-26,2024-08-24,False
7919,MAT07920,Safety Shoes 40 C474,Safety,PPE,FESTO AG,C474-40,KG,HYD01,<NA>,621.130000,XYZ,66.0,2025-02-03,2026-05-05,False
8482,MAT08483,Face Shield 100 A364,Safety,Protection,ABB,A364-100,EA,HYD01,VEN011,291.230000,XYZ,25.0,2025-12-19,2026-03-06,False
8859,MAT08860,Pressure Gauge 150 X871,Instrumentation,Gauge,SIEMENS LTD,X871-150,M,DEL01,VEN012,61.920000,XYZ,55.0,2026-03-13,2026-05-05,False
9076,MAT09077,Tapered Roller Bearing 100 A254,Mechanical,Bearing,EMERSON,A254-100,M,HYD01,VEN006,63.160000,XYZ,64.0,2025-06-08,2026-01-18,False
9113,MAT09114,Servo Motor 40 A745,Electrical,Motor,HONEYWELL,A745-40,EA,AMD01,VEN011,318.910000,XYZ,NaN,2025-12-29,2026-03-25,False
9425,MAT09426,Limit Switch 50 X690,Electrical,Switch,SIEMENS,X690-50,KG,AMD01,VEN048,190.030000,XYZ,8.0,2025-08-23,2025-11-05,False
9444,MAT09445,Helical Gear 100 Z874,Mechanical,Gear,SCHNEIDER,Z874-100,EA,CHE01,VEN031,183.480000,XYZ,62.0,2026-01-05,2026-10-01,False
9667,MAT09668,C554 10 Bearing Ball,Mechanical,Gear,SCHNEIDER ELEC,C463-16,KG,DEL01,VEN037,97.750000,XYZ,72.0,2024-07-13,2024-11-19,False

In [52]:
valid_uom = {
    "EA",
    "KG",
    "M",
    "LTR"
}

df["uom_valid"] = (
    df["uom"].isin(valid_uom)
)

In [53]:
df["price_valid"] = ( df["unit_price"].notna()&(df["unit_price"] > 0))
df["lead_time_valid"] = (
    df["lead_time_days"].notna()&(df["lead_time_days"] >= 0)
)

In [54]:
df["date_valid"] = df["created_date"].notna() & df["last_updated"].notna() & (df["last_updated"] >= df["created_date"])

In [56]:
df["material_id"].duplicated().sum()

np.int64(0)

In [57]:
df["material_id_unique"] = (
    ~df["material_id"].duplicated(keep=False)
)

In [58]:
df[df["material_id_unique"] == False]

Empty DataFrame
Columns: [material_id, material_description, material_category, sub_category, manufacturer, manufacturer_part_no, uom, plant_id, vendor_id, unit_price, currency, lead_time_days, created_date, last_updated, currency_valid, uom_valid, price_valid, lead_time_valid, date_valid, material_id_unique]
Index: []

In [59]:

valid_vendor_ids = set(
    vendor_df["vendor_id"]
    .dropna()
    .astype("string")
    .str.strip()
)

df["vendor_valid"] = (
    df["vendor_id"].notna()
    &
    df["vendor_id"].isin(valid_vendor_ids)
)

In [60]:
valid_plant_ids = set(
    plant_df["plant_id"]
    .dropna()
    .astype("string")
    .str.strip()
)

df["plant_valid"] = (
    df["plant_id"].notna()
    &
    df["plant_id"].isin(valid_plant_ids)
)

In [61]:

required_columns = [
    "material_description",
    "material_category",
    "sub_category",
    "manufacturer",
    "manufacturer_part_no",
    "uom",
    "vendor_id",
    "plant_id",
    "unit_price",
    "currency",
    "lead_time_days"
]

df["completeness_score"] = (
    df[required_columns]
    .notna()
    .sum(axis=1)
    / len(required_columns)
    * 100
).round(2)

In [63]:
df[df['price_valid']==False]

,material_id,material_description,material_category,sub_category,manufacturer,manufacturer_part_no,uom,plant_id,vendor_id,unit_price,...,last_updated,currency_valid,uom_valid,price_valid,lead_time_valid,date_valid,material_id_unique,vendor_valid,plant_valid,completeness_score
68,MAT00069,Fire Extinguisher 200 B470,Safety,Fire,SKF,B470-200,EA,HYD01,VEN052,-670.099625,...,2025-12-02,True,True,False,True,True,True,True,True,100.0
105,MAT00106,Tapered Roller Bearing 80 A446,Mechanical,Bearing,SIEMENS,A446-80,EA,CHE01,VEN068,-1652.086517,...,2025-05-12,False,True,False,True,True,True,True,True,100.0
137,MAT00138,Safety Shoes 25 C241,Safety,PPE,ABB,C241-25,KG,BLR01,VEN022,-4148.530910,...,2026-04-07,True,True,False,True,True,True,True,True,100.0
342,MAT00343,Pressure Sensor 10 B322,Instrumentation,Sensor,PARKER HANNIFIN INDIA,B322-10,M,KOL01,VEN012,-2237.387610,...,2026-08-22,True,True,False,True,True,True,True,True,100.0
724,MAT00725,Pressure Sensor 80 B443,Instrumentation,Sensor,PARKER HANNIFIN,B443-80,EA,BLR01,VEN073,-2721.431445,...,2025-10-22,True,True,False,True,True,True,True,True,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9688,MAT09689,Flexible Coupling 16 B878,Mechanical,Coupling,ABB,B878-16,EA,BLR01,VEN048,-3638.781929,...,2025-10-25,True,True,False,True,True,True,True,True,100.0
9692,MAT09693,Respirator 100 C382,Safety,Protection,HONEYWELL,C382-100,LTR,DEL01,VEN074,-3463.040398,...,2026-07-03,True,True,False,True,True,True,True,True,100.0
9850,MAT09851,Spur Gear 12 X641,Mechanical,Gear,SKF,X641-12,M,AMD01,VEN030,-692.674051,...,2026-04-21,True,True,False,True,True,True,True,True,100.0
9914,MAT09915,Roller Bearing 12 X621,Mechanical,Bearing,EMERSON,X621-12,M,CHE01,VEN063,-4531.177281,...,2024-08-13,True,True,False,True,True,True,True,True,100.0
9978,MAT09979,Gear Coupling 80 Z996,Mechanical,Coupling,THE TIMKEN COMPANY,Z996-80,LTR,CHE01,VEN046,-1233.636827,...,2026-10-01,True,True,False,True,True,True,True,True,100.0

In [64]:
df["missing_manufacturer"] = (
    df["manufacturer"].isna()
)

df["missing_part_no"] = (
    df["manufacturer_part_no"].isna()
)

df["missing_uom"] = (
    df["uom"].isna()
)

df["missing_vendor"] = (
    df["vendor_id"].isna()
)
df["missing_lead_time"] = (
    df["lead_time_days"].isna()
)

In [65]:
duplicate_materials = (
    df["material_id"].duplicated(keep=False).sum()
)

In [66]:
duplicate_materials

np.int64(0)

In [67]:
quality_checks = [
    "material_id_unique",
    "vendor_valid",
    "plant_valid",
    "uom_valid",
    "currency_valid",
    "price_valid",
    "lead_time_valid",
    "date_valid"
]

df["quality_score"] = (
    df[quality_checks]
    .sum(axis=1)
    / len(quality_checks)
    * 100
).round(2)

In [68]:
df

,material_id,material_description,material_category,sub_category,manufacturer,manufacturer_part_no,uom,plant_id,vendor_id,unit_price,...,material_id_unique,vendor_valid,plant_valid,completeness_score,missing_manufacturer,missing_part_no,missing_uom,missing_vendor,missing_lead_time,quality_score
0,MAT00001,Fire Extinguisher 100 X729,Safety,Fire,SKF,X729-100,EA,KOL01,VEN062,274.98,...,True,True,True,100.0,False,False,False,False,False,100.0
1,MAT00002,Control Valve 100 A823,Instrumentation,Valve,SKF,A823-100,M,KOL01,VEN063,56.99,...,True,True,True,100.0,False,False,False,False,False,100.0
2,MAT00003,Control Valve 12 B202,Instrumentation,Valve,BOSCH,B202-12,LTR,PUN01,VEN053,175.06,...,True,True,True,100.0,False,False,False,False,False,100.0
3,MAT00004,Pressure Sensor 100 B641,Instrumentation,Sensor,SKF,B641-100,EA,AMD01,VEN035,202.09,...,True,True,True,100.0,False,False,False,False,False,100.0
4,MAT00005,Safety Shoes 20 Z363,Safety,PPE,ROBERT BOSCH,Z363-20,KG,CHE01,VEN011,457.41,...,True,True,True,100.0,False,False,False,False,False,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,MAT09996,Induction Motor 20 X802,Electrical,Motor,ABB,X802-20,EA,BLR01,VEN029,187.66,...,True,True,True,100.0,False,False,False,False,False,100.0
9996,MAT09997,AC Motor 10 C724,Electrical,Motor,ABB,C724-10,KG,CHE01,VEN031,1318.09,...,True,True,True,100.0,False,False,False,False,False,100.0
9997,MAT09998,Roller Bearing 200 A760,Mechanical,Bearing,SCHNEIDER,A760-200,EA,CHE01,VEN039,181.64,...,True,True,True,100.0,False,False,False,False,False,100.0
9998,MAT09999,Flexible Coupling 25 Z383,Mechanical,Coupling,SIEMENS,Z383-25,EA,KOL01,VEN080,351.02,...,True,True,True,100.0,False,False,False,False,False,100.0
9999,MAT10000,Fire Extinguisher 16 X817,Safety,Fire,SIEMENS,X817-16,EA,HYD01,VEN039,259.80,...,True,True,True,100.0,False,False,False,False,False,100.0

In [69]:
def quality_status(score):

    if score >= 90:
        return "Good"

    elif score >= 70:
        return "Needs Review"

    else:
        return "Critical"


df["quality_status"] = (
    df["quality_score"]
    .apply(quality_status)
)

In [73]:
df[df['quality_status']=='Critical']

Empty DataFrame
Columns: [material_id, material_description, material_category, sub_category, manufacturer, manufacturer_part_no, uom, plant_id, vendor_id, unit_price, currency, lead_time_days, created_date, last_updated, currency_valid, uom_valid, price_valid, lead_time_valid, date_valid, material_id_unique, vendor_valid, plant_valid, completeness_score, missing_manufacturer, missing_part_no, missing_uom, missing_vendor, missing_lead_time, quality_score, quality_status]
Index: []

[0 rows x 30 columns]

In [74]:

clean_material_df = df.copy()


# Remove technical validation columns
technical_columns = [
    "currency_valid",
    "uom_valid",
    "price_valid",
    "lead_time_valid",
    "date_valid",
    "material_id_unique",
    "vendor_valid",
    "plant_valid"
]

clean_material_df = clean_material_df.drop(
    columns=technical_columns,
    errors="ignore"
)


# ============================================================
# 27. CLEAN VENDOR MASTER
# ============================================================

clean_vendor_df = vendor_df.copy()

for col in clean_vendor_df.columns:

    if clean_vendor_df[col].dtype == "object":

        clean_vendor_df[col] = (
            clean_vendor_df[col]
            .astype("string")
            .str.strip()
        )

clean_vendor_df = clean_vendor_df.replace(
    missing_values,
    pd.NA
)


# ============================================================
# 28. CLEAN PLANT MASTER
# ============================================================

clean_plant_df = plant_df.copy()

for col in clean_plant_df.columns:

    if clean_plant_df[col].dtype == "object":

        clean_plant_df[col] = (
            clean_plant_df[col]
            .astype("string")
            .str.strip()
        )

clean_plant_df = clean_plant_df.replace(
    missing_values,
    pd.NA
)

In [75]:
clean_material_df.to_csv(
    "material_master_cleaned.csv",
    index=False
)

clean_vendor_df.to_csv(
    "vendor_master_cleaned.csv",
    index=False
)

clean_plant_df.to_csv(
    "plant_master_cleaned.csv",
    index=False
)